// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogininvaliduserTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeTest
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterTest
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logininvaliduser() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,1000)");
    js.executeScript("window.scrollTo(0,1875)");
    driver.findElement(By.cssSelector(".l-GwW:nth-child(1) > .VS-Ex .D8VyR")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".l-GwW:nth-child(1) > .VS-Ex path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".YSmsd > .M3v0L")).click();
    driver.findElement(By.cssSelector(".VS-Ex:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".VS-Ex:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("phone_field")).click();
    driver.findElement(By.id("phone_field")).sendKeys("+380 (_0) 000-00-0_");
    driver.findElement(By.id("phoneConfirmButton")).click();
    driver.findElement(By.cssSelector(".\\_7Fcq2")).click();
  }
}
