// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistercheckinvalidmassageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeTest
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterTest
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registercheckinvalidmassage() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".l-GwW:nth-child(1) > .VS-Ex")).click();
    driver.findElement(By.cssSelector(".VS-Ex:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".\\_0cNvO:nth-child(2)")).click();
    driver.findElement(By.id("firstName")).sendKeys("12");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("+380 (11) 111-11-11");
    driver.findElement(By.cssSelector(".uV711")).click();
    driver.findElement(By.id("subscribe")).click();
    driver.findElement(By.cssSelector(".NI39K > .M3v0L:nth-child(5)")).click();
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("1");
    driver.findElement(By.id("registrationConfirmButton")).click();
    driver.findElement(By.cssSelector(".NI39K > .M3v0L > .M3v0L:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".M3v0L > .M3v0L > .M3v0L:nth-child(3) > div > .M3v0L > .\\_3Trjq")).click();
    driver.findElement(By.cssSelector(".\\_7Fcq2")).click();
  }
}
